// The FAQ, in one place. The landing page renders it AND client/index.html
// carries it as FAQPage structured data — those two must say the same thing
// word for word, or Google treats the markup as describing content that
// isn't on the page. They had already drifted apart once. ops/sync-faq-jsonld.mjs
// regenerates the markup from here, and test/faq_jsonld_matches.mjs fails the
// build if they diverge again.
export const FAQS = [
  { cat: 'General', q: 'What is Collarone?', a: 'Fifteen business suites behind one login, priced and billed in naira: HR, payroll and benefits, invoicing, CRM, inventory, compliance and more. Your company gets its own isolated workspace, and you switch on only the suites you need.' },
  { cat: 'General', q: 'Can I try it before paying anything?', a: 'Yes. Open the demo from the menu, pick a suite, and you land inside it: real screens, sample data, and a guided tour that assumes you\'ve never seen it before. No sign-up, nothing to install, and you can\'t break anything.' },
  { cat: 'General', q: 'How long does it take to get started?', a: 'Minutes. Sign up, pick your plan and suites, and your workspace is created straight away. During early access we also set things up with you personally on WhatsApp. Most businesses are live the same day.' },
  { cat: 'Pricing', q: 'How much does Collarone cost?', a: 'Every tier is à la carte. You pick the suites. Startup is ₦15,000/month with any 3 suites included, Standard is ₦25,000 with 5, and extra suites cost ₦8,000 or ₦6,000 each by tier. Add ₦2,000 per staff member, save 15% by paying yearly, and your rate locks in at sign-up, with no dollar pricing or forex markup. Enterprise is quote-based: tell us what you want to run under Collarone and we scope it with dedicated onboarding.' },
  { cat: 'Pricing', q: 'Is Collarone only for large companies?', a: 'No. It starts at a corner-shop size. Startup is ₦15,000 a month, and every suite ships complete, not as a stripped-down trial. A 5-person team gets the same payroll engine and the same CRM an enterprise gets.' },
  { cat: 'Pricing', q: 'Is there a contract, or can I cancel anytime?', a: 'No long-term contract. Collarone is billed monthly, or yearly for 15% off. And the rate you sign up at is locked: it never changes for you, even when our published prices do.' },
  { cat: 'Pricing', q: 'What happens if I miss a renewal?', a: 'Nothing dramatic. You get a grace window with full access and clear reminders; after that your workspace turns read-only (everything still visible, nothing deletable) until you renew. We never delete your data over a late payment.' },
  { cat: 'Product', q: 'Does Collarone include a website builder?', a: 'Yes, on every tier. Pick from 11 designed themes across online store, landing page and company-profile categories, edit every word and picture in place, and sell with a real cart: transfer, pay on delivery, or card through your own Paystack account. Already have a site? Link it instead.' },
  { cat: 'Product', q: 'Is there a CRM for managing customers?', a: 'Yes. Contacts, companies, a WhatsApp-first activity log, a deals pipeline valued in naira, a bookings day-sheet, and a Money Owed tracker that ages what customers owe you. Enquiries from your website land in it automatically, so nothing gets ignored.' },
  { cat: 'Product', q: 'Can Collarone run my hiring end to end?', a: 'Yes. Post a role to your public careers page, move applicants through a pipeline with interview scorecards, send the offer as a private link they accept online, then hire in one click: their staff login is created instantly and onboarding starts.' },
  { cat: 'Product', q: 'Can Collarone write my company letters?', a: 'Yes. The Letters engine drafts confirmation, promotion, verification, query and warning letters, from templates or with Collarone AI, rendered on your letterhead with your logo and authorised signature, auto-numbered, and filed into Documents automatically.' },
  { cat: 'Product', q: 'What about payroll?', a: 'Payroll runs the 2026 Nigeria Tax Act rules (the new PAYE bands with the ₦800,000 exemption and rent relief) plus pension, NHF and NSITF, payslips, and staff loans that repay themselves by deduction. Benefits live in the same suite: HMO, pension and custom benefits, switchable per person. Collarone never touches your bank account. It prepares the disbursement, your bank executes it.' },
  { cat: 'Product', q: 'Can I generate invoices and automate follow-ups?', a: 'Yes. Create a numbered invoice and share it as a link your customer can pay from, by transfer or by card straight into your own Paystack account. Receipts, GRNs, stock passes and signed handover notes come from the same engine, on your letterhead. Automation then does the chasing: overdue-invoice reminders, low-stock alerts and follow-up tasks, daily.' },
  { cat: 'Product', q: 'Does it help with tax deadlines?', a: 'Yes. The Compliance Calendar tracks Nigeria\'s statutory dates: PAYE by the 10th, VAT by the 21st, pension, NHF, NSITF, and annual filings like CAC returns. Each month you mark them done with a reference, so “did we file?” always has an answer with a name on it.' },
  { cat: 'Security', q: 'Is my company’s data secure?', a: 'Every screen checks who is allowed to see it before showing anything, and every company\'s data is isolated from every other company\'s at the database level, verified directly, not assumed. And Collarone never holds or moves your money; payments settle in your own accounts.' },
];
